[workspace]
members = [
    "clear-mind-cli",
    "clear-mind-core",
]

[workspace.package]
version = "0.1.0"
authors = ["Vlad Stepanov <8uk.8ak@gmail.com>"]
description = "Podcast player which tries to help you to focus on the content."
license = "MIT"

[profile.release]
debug = true
